/* The viewers' words in French, the `locale="fr"` base of `AgentWorkspace`'s viewers. Typed as `ViewerLabels`, so a key added in English must be added here too. */
import type { ViewerLabels } from './viewer-window';

export const frenchViewerLabels: ViewerLabels = {
  share: 'Partager',
  moreActions: 'Plus d’actions',
  reload: 'Recharger',
  copy: 'Copier',
  download: 'Télécharger',
  openInNewTab: 'Ouvrir dans un nouvel onglet',
  enterFullscreen: 'Plein écran',
  exitFullscreen: 'Quitter le plein écran',
  close: 'Fermer',
  readOnly: 'Lecture seule',
  refreshFailed: 'Échec de l’actualisation',
  shareFailed: 'Partage impossible',
  linkCopied: 'Lien copié',
  shared: 'Partagé',
  copied: 'Copié',
  copyFailed: 'Copie impossible',
  actionFailed: 'L’action a échoué',
  manualCopy: link => `Ce navigateur a bloqué la copie automatique. Copiez ${link ? 'le lien' : 'le texte'} ci-dessous.`,
  done: 'Terminé',
  versionHistory: 'Historique des versions',
  latest: 'Dernière version',
  loading: 'Chargement…',
  saved: 'Enregistré',
  unsaved: 'Non enregistré',
  saving: 'Enregistrement',
  saveUnconfirmed: 'Enregistrement non confirmé',
  changedElsewhere: 'Modifié ailleurs',
  closed: 'Fermé',
  save: 'Enregistrer',
  checkSave: 'Vérifier l’enregistrement',
  abandon: 'Abandonner et actualiser, en gardant mon brouillon',
  discardLocal: 'Annuler mes modifications',
  view: 'Affichage',
  preview: 'Aperçu',
  source: 'Source',
  htmlPreview: 'Aperçu HTML',
  htmlSource: 'Source HTML',
  editorMode: 'Mode d’édition',
  rich: 'Mise en forme',
  richText: 'Texte mis en forme',
  markdownSource: 'Source Markdown',
  document: 'Document',
  zoom: 'Zoom',
  zoomIn: 'Agrandir',
  zoomOut: 'Réduire',
  zoomLevel: percent => `Zoom ${percent}, ajuster à la vue`,
  fitToView: 'Ajuster à la vue',
  actualSize: 'Taille réelle',
  imageUnreadable: 'Ce fichier n’a pas pu être lu comme une image.',
  imageUnsupported: mediaType => `Ce type d’image (${mediaType || 'inconnu'}) ne peut pas être affiché ici. Vous pouvez toujours le télécharger.`,
  imageStage: name => `Image ${name}`,
  pdfUnsupported: 'Ce navigateur ne peut pas afficher les PDF directement.',
  pdfHint: (name, canOpen) => `Téléchargez ${name} pour le lire dans une application PDF${canOpen ? ', ou ouvrez-le dans un nouvel onglet' : ''}.`,
  notSaved: reason => `Non enregistré : ${reason}`,
  saveFailedReason: 'l’enregistrement a échoué',
  changedElsewhereReason: 'modifié ailleurs',
  operationFailed: 'L’opération sur le document a échoué. Votre source est conservée.',
};
