import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:5213', { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForTimeout(2000);
await page.keyboard.press('Meta+Shift+K');
await page.waitForTimeout(300);
const before = await page.evaluate(() => document.activeElement?.textContent ?? '');
await page.keyboard.press('ArrowDown');
await page.waitForTimeout(300);
const afterDown = await page.evaluate(() => document.activeElement?.textContent ?? '');
await page.screenshot({ path: '/tmp/boring-workspace-picker-after-down.png', fullPage: true });
console.log(JSON.stringify({ before, afterDown, menuVisible: await page.locator('[data-slot="dropdown-menu-content"]').isVisible().catch(() => false) }));
await browser.close();
