export const SHAREPOINT_ERROR_CODES = {
  AUTH_REQUIRED: "SHAREPOINT_AUTH_REQUIRED",
  ADMIN_CONSENT_REQUIRED: "SHAREPOINT_ADMIN_CONSENT_REQUIRED",
  PREVIEW_UNAVAILABLE: "SHAREPOINT_PREVIEW_UNAVAILABLE",
  PREVIEW_TOKEN_REDACTED: "SHAREPOINT_PREVIEW_TOKEN_REDACTED",
  FILE_NOT_FOUND: "SHAREPOINT_FILE_NOT_FOUND",
  EDIT_CONFLICT: "SHAREPOINT_EDIT_CONFLICT",
  PROVIDER_UNAVAILABLE: "SHAREPOINT_PROVIDER_UNAVAILABLE",
  PROVIDER_TOOL_FAILED: "SHAREPOINT_PROVIDER_TOOL_FAILED",
  INVALID_REF: "SHAREPOINT_INVALID_REF",
  REF_CONTAINS_SECRET: "SHAREPOINT_REF_CONTAINS_SECRET",
} as const

export type SharePointErrorCode = typeof SHAREPOINT_ERROR_CODES[keyof typeof SHAREPOINT_ERROR_CODES]

export class SharePointRefValidationError extends Error {
  readonly code: SharePointErrorCode

  constructor(code: SharePointErrorCode, message: string) {
    super(message)
    this.name = "SharePointRefValidationError"
    this.code = code
  }
}
