/* The chat's words in French, the `locale="fr"` base of `PiChat`, `AmbientChat` and `AgentWorkspace`. Typed as `ChatLabels`, so a key added in English must be added here too. */
import type { ChatLabels } from './labels';

const TOOL_VERBS: Readonly<Record<string, string>> = { read: 'Lecture', write: 'Écriture', edit: 'Modification', ls: 'Liste', list_files: 'Liste', find: 'Recherche', grep: 'Recherche', load_skill: 'Chargement de la compétence', bash: 'Exécution bash' };
const TOOL_NOUNS: Readonly<Record<string, string>> = { bash: 'commande', read: 'lecture', write: 'écriture', edit: 'modification', find: 'recherche', grep: 'recherche', ls: 'liste' };
const EFFORT_NAMES: Readonly<Record<string, string>> = { off: 'Désactivé', minimal: 'Minimal', low: 'Faible', medium: 'Moyen', high: 'Élevé', xhigh: 'Très élevé', max: 'Maximum' };
const EFFORT_DETAILS: Readonly<Record<string, string>> = { off: 'Sans réflexion supplémentaire', minimal: 'Presque aucune réflexion', low: 'Réflexion légère', medium: 'Réflexion équilibrée', high: 'Réflexion approfondie', xhigh: 'Réflexion très approfondie', max: 'Réflexion maximale' };

export const frenchChatLabels: ChatLabels = {
  title: 'Conversation',
  history: 'Historique',
  live: 'En direct',
  connecting: 'Connexion…',
  reconnecting: 'Reconnexion…',
  loadFailed: 'La conversation n’a pas pu être chargée.',
  disconnected: 'Déconnecté. Les derniers messages reçus restent affichés.',
  reconnect: 'Se reconnecter',
  requiredActions: 'Actions requises dans la conversation',
  messages: 'Messages',
  showEarlier: 'Afficher les messages précédents',
  loading: 'Chargement de la conversation…',
  emptyDescription: 'Commencez une conversation.',
  jumpToLatest: 'Aller au dernier message',
  agentWorking: 'L’agent travaille',
  waitingForAnswer: 'En attente de votre réponse',
  retryPending: 'Nouvelle tentative en attente',
  compacting: 'Résumé du contexte en cours',
  moreActions: 'Plus d’actions',
  sendUnknown: 'L’envoi n’est pas confirmé. Le message est conservé jusqu’à ce que vous le vérifiiez ou le renvoyiez.',
  checkSubmission: 'Vérifier l’envoi',
  retrySame: 'Renvoyer la même demande',
  stopRequested: 'Arrêt demandé. En attente de confirmation.',
  stopUnconfirmed: 'Arrêt non confirmé. Le travail continue peut-être.',
  steerRefused: 'Le message n’a pas pu être ajouté en cours de réponse ; il est revenu dans la zone de saisie.',
  tooLate: 'Trop tard : ce message a déjà commencé.',
  tooLateToRemove: 'Trop tard pour le retirer : ce message a déjà commencé.',
  queueFailed: 'Le message n’a pas pu être modifié.',
  queueLocked: 'Les messages en attente ne peuvent pas être modifiés ici.',
  waitToSteer: 'Attendez la fin de l’envoi en cours, puis réessayez.',
  steerFailed: 'Le message n’a pas pu être ajouté en cours de réponse.',
  connectionFailed: 'Échec de la connexion',
  actionFailedShort: 'Échec de l’action',
  uploadFailedShort: 'Échec de l’envoi',
  changeRefused: 'La modification a été refusée',
  dismissHint: 'cliquez pour fermer',
  placeholder: 'Écrivez à l’agent…',
  placeholderWorking: 'Mettre un message en attente…',
  messageInput: 'Message',
  send: 'Envoyer',
  sendHint: 'Envoyer (Entrée)',
  stop: 'Arrêter',
  queue: 'Mettre en attente',
  add: 'Ajouter',
  attachFiles: 'Joindre des fichiers',
  // Voice input (the microphone button beside the composer)
  voiceRecord: 'Enregistrer un message',
  voiceStop: 'Arrêter l’enregistrement',
  voiceCancel: 'Annuler l’enregistrement',
  voiceTranscribing: 'Transcription…',
  voiceNothingHeard: 'Rien n’a été entendu. Réessayez.',
  voiceTranscribeFailed: 'L’enregistrement n’a pas pu être transcrit. Réessayez.',
  voiceDenied: 'Microphone bloqué. Autorisez-le pour ce site dans le navigateur, puis appuyez de nouveau sur enregistrer.',
  voiceNoMicrophone: 'Aucun microphone trouvé. Branchez-en un, puis appuyez de nouveau sur enregistrer.',
  voiceBusy: 'Le microphone est occupé ou n’a pas pu être ouvert. Fermez les autres applications qui l’utilisent et réessayez.',
  voiceInsecure: 'L’enregistrement exige une page sécurisée (https ou localhost).',
  voiceUnsupported: 'Ce navigateur ne peut pas enregistrer le son ici.',
  voiceStartFailed: 'Le microphone n’a pas pu être démarré.',
  commands: 'Commandes',
  feedback: 'Retour',
  feedbackHint: 'Retour : montrez l’endroit de la page et dites ce qui ne va pas',
  remove: name => `Retirer ${name}`,
  dismiss: name => `Fermer ${name}`,
  uploading: name => `Envoi de ${name}…`,
  uploadFailed: (name, error) => `${name} : ${error ?? 'échec de l’envoi'}`,
  preparingAttachments: 'Préparation des pièces jointes…',
  preparingAttachmentsShort: 'Préparation des pièces jointes',
  mentionedFiles: 'Fichiers mentionnés',
  uploads: 'Envois',
  attachments: 'Pièces jointes',
  searchCommands: 'Rechercher une commande',
  filterBySource: 'Filtrer par source',
  allSources: 'Toutes',
  noCommands: 'Aucune commande ne correspond.',
  slashGroup: group => group === 'skills' ? 'compétences' : group === 'built-in' ? 'intégrées' : group,
  skillBadge: 'compétence',
  workspaceFiles: 'Fichiers de l’espace',
  searchFailed: 'La recherche a échoué',
  model: 'Modèle',
  effort: 'Effort',
  effortDefault: 'Par défaut',
  modelAndEffort: 'Modèle et effort',
  modelSummary: (model, effort) => [model && `Modèle : ${model}`, effort && `Effort : ${effort}`].filter(Boolean).join(', '),
  effortName: level => EFFORT_NAMES[level] ?? level,
  effortDetail: level => EFFORT_DETAILS[level],
  queuedMessages: 'Messages en attente',
  steer: 'Envoyer maintenant',
  steerHint: 'Ajouter ce message à la réponse en cours',
  steering: 'Envoi en cours de réponse',
  queued: 'En attente',
  removeQueued: 'Retirer le message en attente',
  removeHint: 'Retirer',
  more: 'Plus',
  edit: 'Modifier',
  sending: 'Envoi',
  images: count => `[${count} image${count === 1 ? '' : 's'}]`,
  historyDialog: 'Historique des conversations',
  newConversation: 'Nouvelle',
  untitled: 'Nouvelle conversation',
  closeHistory: 'Fermer l’historique',
  close: 'Fermer',
  earlierInConversation: 'Messages précédents de cette conversation',
  searchConversations: 'Rechercher une conversation',
  archived: 'Archivées',
  current: 'En cours',
  noMatch: query => `Aucune conversation ne correspond à « ${query} ».`,
  noArchived: 'Aucune conversation archivée.',
  noConversations: 'Aucune conversation pour le moment.',
  loadingConversations: 'Chargement des conversations…',
  actionFailed: 'Cela n’a pas fonctionné. Réessayez.',
  rename: 'Renommer',
  renameItem: title => `Renommer ${title}`,
  conversationName: 'Nom de la conversation',
  save: 'Enregistrer',
  archive: 'Archiver',
  restore: 'Restaurer',
  archiveItem: (title, archived) => `${archived ? 'Restaurer' : 'Archiver'} ${title}`,
  delete: 'Supprimer',
  deleteItem: title => `Supprimer ${title}`,
  keep: 'Garder la conversation',
  today: 'Aujourd’hui',
  yesterday: 'Hier',
  previousWeek: 'Les 7 derniers jours',
  older: 'Plus anciennes',
  conversations: 'Conversations',
  earlierMessages: 'Messages précédents',
  readOnly: '(lecture seule)',
  retry: 'Réessayer',
  loadingShort: 'Chargement…',
  loadEarlier: 'Charger les précédents',
  returnToConversation: 'Revenir à la conversation en cours',
  historyFailed: 'L’historique n’a pas pu être chargé. La page précédente reste affichée.',
  loadPage: 'Chargez une page pour parcourir les messages précédents.',
  noRecords: 'Aucun élément sur cette page d’historique.',
  beginning: 'Début de la conversation.',
  justNow: 'à l’instant',
  roleSystem: 'Système',
  roleToolResult: (tool, failed) => `Résultat de l’outil : ${tool}${failed ? ' (échec)' : ''}`,
  roleUser: 'Vous',
  roleAssistant: outcome => outcome === 'interrupted' ? 'Assistant (interrompu)' : outcome === 'failed' ? 'Assistant (échec)' : 'Assistant',
  roleEvent: 'Événement',
  contextBoundary: 'Limite du contexte',
  copy: 'Copier',
  copied: 'Copié',
  copyFailed: 'Échec de la copie',
  failed: 'Échec',
  copyResponse: 'Copier la réponse',
  copyCode: 'Copier le code',
  fork: 'Repartir d’ici',
  forkHint: 'Repartir d’ici : une nouvelle conversation avec les messages jusqu’à cette réponse',
  responseFailed: 'La réponse a échoué',
  interrupted: 'Réponse interrompue',
  thinking: 'Réflexion…',
  openImage: 'Ouvrir l’image jointe',
  imageAttachment: 'Image jointe',
  systemContext: 'Contexte système',
  toolFailed: tool => `Échec de ${tool}`,
  event: label => `Événement : ${label}`,
  reasoning: 'Réflexion',
  thinkingStep: 'Réflexion',
  steps: count => `${count} ${count === 1 ? 'étape' : 'étapes'}`,
  toolRunning: 'En cours',
  toolCompleted: 'Terminé',
  toolFailedStatus: 'Échec',
  toolUnfinished: 'Sans résultat',
  arguments: 'Arguments',
  result: 'Résultat',
  error: 'Erreur',
  openImageResult: 'Ouvrir l’image du résultat',
  emptyResult: 'Résultat vide',
  toolActivity: (tool, hint) => {
    const verb = TOOL_VERBS[tool] ?? `Exécution de ${tool}`;
    return hint ? `${verb}${tool === 'bash' ? ' :' : ''} ${hint}` : verb;
  },
  toolNoun: tool => TOOL_NOUNS[tool] ?? tool,
  approvalNeeded: 'Approbation requise',
  needsApproval: 'Votre approbation est nécessaire',
  approve: 'Approuver',
  deny: 'Refuser',
  approved: 'Approuvé',
  denied: 'Refusé',
  notDecided: 'Non décidé : l’exécution a été arrêtée',
  wantsToRun: 'L’agent souhaite exécuter',
  decision: 'Décision',
  stillWritingCall: 'L’agent est encore en train d’écrire cet appel…',
  decidingUnavailable: 'La décision n’est pas disponible dans cette vue.',
  decisionSent: approved => `${approved ? 'Approuvé.' : 'Refusé.'} En attente de l’agent…`,
  decisionRefused: kind => kind === 'denied' ? 'Cette réponse n’a pas été acceptée.' : kind === 'conflict' ? 'Cet appel a déjà été décidé.' : 'Cet appel n’attend plus de décision.',
  decisionNotSent: 'La décision n’a pas pu être envoyée.',
  waitingForAgent: 'En attente de l’agent…',
  question: 'Question',
  questionForYou: 'Une question pour vous',
  notAnswered: 'Sans réponse',
  answered: 'Répondu',
  askedQuestion: 'L’agent a posé une question.',
  answerOptions: 'Réponses possibles',
  ownAnswer: 'Ou écrivez votre propre réponse',
  typeAnswer: 'Écrivez votre réponse',
  yourAnswerInput: 'Votre réponse',
  answer: 'Répondre',
  stillWritingQuestion: 'L’agent est encore en train d’écrire cette question…',
  answeringUnavailable: 'La réponse n’est pas disponible dans cette vue.',
  answerRefused: kind => kind === 'denied' ? 'Cette réponse n’a pas été acceptée.' : kind === 'conflict' ? 'Cette question a déjà reçu une réponse.' : 'Cette question n’attend plus de réponse.',
  answerNotSent: 'La réponse n’a pas pu être envoyée.',
  yourAnswer: 'Votre réponse :',
  artifact: 'Document',
  opening: 'Ouverture…',
  viewing: 'Affiché',
  version: ordinal => `Version ${ordinal}`,
  runCommand: (name, execute) => `${execute ? 'Exécuter' : 'Insérer'} la commande /${name}`,
  taskStatus: 'État de la tâche',
  activityFailed: (count, tools) => `${count > 1 ? `${count} étapes ont échoué` : 'Une étape a échoué'} : ${tools}`,
  activityUsed: (summary, stopped) => `${stopped ? 'Arrêté · ' : 'Utilisé : '}${summary}`,
  activityThought: 'Réflexion terminée',
  activityMany: steps => `${steps} étapes réalisées`,
  open: 'Ouvrir',
  openArtifact: (title, version) => version === undefined ? `Ouvrir ${title}` : `Ouvrir ${title}, version ${version}`,
};
