export const TASK_ERROR_CODES = {
  TASK_SOURCE_ERROR: "TASK_SOURCE_ERROR",
  TASK_SOURCE_NOT_FOUND: "TASK_SOURCE_NOT_FOUND",
  TASK_SOURCE_MOVE_UNSUPPORTED: "TASK_SOURCE_MOVE_UNSUPPORTED",
  TASK_INVALID_BODY: "TASK_INVALID_BODY",
  TASK_SESSION_NOT_FOUND: "TASK_SESSION_NOT_FOUND",
} as const

export type TaskErrorCode = typeof TASK_ERROR_CODES[keyof typeof TASK_ERROR_CODES]
