---
- name: restart postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ pg_version }}-main"
    state: restarted

- name: reload postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ pg_version }}-main"
    state: reloaded
