export const FULL_PAGE_PANEL_MISSING_COMPONENT = "FULL_PAGE_PANEL_MISSING_COMPONENT"
export const FULL_PAGE_PANEL_INVALID_PARAMS_JSON = "FULL_PAGE_PANEL_INVALID_PARAMS_JSON"
export const FULL_PAGE_PANEL_PARAMS_NOT_OBJECT = "FULL_PAGE_PANEL_PARAMS_NOT_OBJECT"
export const FULL_PAGE_PANEL_UNKNOWN_COMPONENT = "FULL_PAGE_PANEL_UNKNOWN_COMPONENT"
export const FULL_PAGE_PANEL_NOT_SUPPORTED = "FULL_PAGE_PANEL_NOT_SUPPORTED"
export const FULL_PAGE_PANEL_RENDER_FAILED = "FULL_PAGE_PANEL_RENDER_FAILED"

export type WorkspaceFullPageRouteErrorCode =
  | typeof FULL_PAGE_PANEL_MISSING_COMPONENT
  | typeof FULL_PAGE_PANEL_INVALID_PARAMS_JSON
  | typeof FULL_PAGE_PANEL_PARAMS_NOT_OBJECT
  | typeof FULL_PAGE_PANEL_UNKNOWN_COMPONENT
  | typeof FULL_PAGE_PANEL_NOT_SUPPORTED
  | typeof FULL_PAGE_PANEL_RENDER_FAILED
