export const ERROR_CODE_INVALID_PATH = 'invalid_path'
export const ERROR_CODE_VALIDATION_ERROR = 'validation_error'
export const ERROR_CODE_PATH_REJECTED = 'path_rejected'
export const ERROR_CODE_NOT_FOUND = 'not_found'
export const ERROR_CODE_ALREADY_EXISTS = 'already_exists'
export const ERROR_CODE_CONFLICT = 'conflict'
export const ERROR_CODE_INTERNAL = 'internal'
