export const OBJECTIVE_ERROR_CODES = {
  NOT_FOUND: "OBJECTIVE_NOT_FOUND",
  VALIDATION_INVALID: "OBJECTIVE_VALIDATION_INVALID",
  REVISION_CONFLICT: "OBJECTIVE_REVISION_CONFLICT",
  PATH_ESCAPE: "OBJECTIVE_PATH_ESCAPE",
  TOO_LARGE: "OBJECTIVE_TOO_LARGE",
  LOCK_TIMEOUT: "OBJECTIVE_LOCK_TIMEOUT",
} as const

export type ObjectiveErrorCode = (typeof OBJECTIVE_ERROR_CODES)[keyof typeof OBJECTIVE_ERROR_CODES]

export const OBJECTIVE_ERROR_CODE_VALUES = Object.values(OBJECTIVE_ERROR_CODES) as ObjectiveErrorCode[]
