/**
 * Drizzle ORM relations — generated by `drizzle-kit pull` from the Neon production DB.
 */
import { relations } from 'drizzle-orm/relations'
import {
  workspaces,
  workspaceRuntimes,
  workspaceInvites,
  workspaceSettings,
  workspaceMembers,
} from './schema.js'

export const workspaceRuntimesRelations = relations(
  workspaceRuntimes,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceRuntimes.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspacesRelations = relations(workspaces, ({ many }) => ({
  workspaceRuntimes: many(workspaceRuntimes),
  workspaceInvites: many(workspaceInvites),
  workspaceSettings: many(workspaceSettings),
  workspaceMembers: many(workspaceMembers),
}))

export const workspaceInvitesRelations = relations(
  workspaceInvites,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceInvites.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspaceSettingsRelations = relations(
  workspaceSettings,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceSettings.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspaceMembersRelations = relations(
  workspaceMembers,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceMembers.workspaceId],
      references: [workspaces.id],
    }),
  }),
)
