/**
 * Drizzle ORM schema — generated by `drizzle-kit pull` from the Neon production DB.
 *
 * Generated: 2026-03-25 (bd-fus66)
 * Tables: workspaces, workspace_runtimes, workspace_invites, workspace_settings,
 *         workspace_members, user_settings
 *
 * DO NOT modify schema during dual-stack period.
 * Both Python and TS servers read/write the same tables.
 * Drizzle migrations only AFTER Python is fully removed (Phase 7).
 *
 * Manual fixes applied to drizzle-kit output:
 * - workspace_settings.value: bytea → customType (drizzle-kit couldn't parse)
 * - user_settings.email/displayName: fixed malformed default strings
 * - check constraints: fixed extra closing parentheses in SQL
 */
import {
  pgTable,
  index,
  uniqueIndex,
  uuid,
  text,
  timestamp,
  boolean,
  foreignKey,
  check,
  primaryKey,
  jsonb,
  customType,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

// Custom type for bytea (encrypted workspace settings)
const bytea = customType<{ data: Buffer }>({
  dataType() {
    return 'bytea'
  },
})

// --- Tables ---

export const workspaces = pgTable(
  'workspaces',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    appId: text('app_id').default('boring-ui').notNull(),
    name: text().notNull(),
    createdBy: uuid('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
    isDefault: boolean('is_default').default(false).notNull(),
    machineId: text('machine_id'),
    volumeId: text('volume_id'),
    flyRegion: text('fly_region').default('cdg'),
  },
  (table) => [
    index('idx_workspaces_app_id').using(
      'btree',
      table.appId.asc().nullsLast().op('text_ops'),
    ),
    index('idx_workspaces_created_by').using(
      'btree',
      table.createdBy.asc().nullsLast().op('uuid_ops'),
    ),
    uniqueIndex('idx_workspaces_default_per_user_app')
      .using(
        'btree',
        table.createdBy.asc().nullsLast().op('text_ops'),
        table.appId.asc().nullsLast().op('uuid_ops'),
      )
      .where(sql`(is_default = true)`),
    index('idx_workspaces_machine_id')
      .using('btree', table.machineId.asc().nullsLast().op('text_ops'))
      .where(sql`(machine_id IS NOT NULL)`),
  ],
)

export const workspaceRuntimes = pgTable(
  'workspace_runtimes',
  {
    workspaceId: uuid('workspace_id').primaryKey().notNull(),
    spriteUrl: text('sprite_url'),
    spriteName: text('sprite_name'),
    state: text().default('pending').notNull(),
    lastError: text('last_error'),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    provisioningStep: text('provisioning_step'),
    stepStartedAt: timestamp('step_started_at', {
      withTimezone: true,
      mode: 'string',
    }),
  },
  (table) => [
    foreignKey({
      columns: [table.workspaceId],
      foreignColumns: [workspaces.id],
      name: 'workspace_runtimes_workspace_id_fkey',
    }),
    check(
      'workspace_runtimes_state_check',
      sql`state = ANY (ARRAY['pending'::text, 'provisioning'::text, 'ready'::text, 'error'::text])`,
    ),
  ],
)

export const workspaceInvites = pgTable(
  'workspace_invites',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    workspaceId: uuid('workspace_id').notNull(),
    email: text().notNull(),
    tokenHash: text('token_hash').notNull(),
    role: text().default('editor').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'string' }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true, mode: 'string' }),
    createdBy: uuid('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('idx_workspace_invites_email').using(
      'btree',
      table.email.asc().nullsLast().op('text_ops'),
    ),
    uniqueIndex('idx_workspace_invites_token_hash').using(
      'btree',
      table.tokenHash.asc().nullsLast().op('text_ops'),
    ),
    index('idx_workspace_invites_workspace_id').using(
      'btree',
      table.workspaceId.asc().nullsLast().op('uuid_ops'),
    ),
    foreignKey({
      columns: [table.workspaceId],
      foreignColumns: [workspaces.id],
      name: 'workspace_invites_workspace_id_fkey',
    }),
    check(
      'workspace_invites_role_check',
      sql`role = ANY (ARRAY['owner'::text, 'editor'::text, 'viewer'::text])`,
    ),
  ],
)

export const workspaceSettings = pgTable(
  'workspace_settings',
  {
    workspaceId: uuid('workspace_id').notNull(),
    key: text().notNull(),
    value: bytea('value').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.workspaceId],
      foreignColumns: [workspaces.id],
      name: 'workspace_settings_workspace_id_fkey',
    }),
    primaryKey({
      columns: [table.workspaceId, table.key],
      name: 'workspace_settings_pkey',
    }),
  ],
)

export const workspaceMembers = pgTable(
  'workspace_members',
  {
    workspaceId: uuid('workspace_id').notNull(),
    userId: uuid('user_id').notNull(),
    role: text().default('owner').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.workspaceId],
      foreignColumns: [workspaces.id],
      name: 'workspace_members_workspace_id_fkey',
    }),
    primaryKey({
      columns: [table.workspaceId, table.userId],
      name: 'workspace_members_pkey',
    }),
    check(
      'workspace_members_role_check',
      sql`role = ANY (ARRAY['owner'::text, 'editor'::text, 'viewer'::text])`,
    ),
  ],
)

export const userSettings = pgTable(
  'user_settings',
  {
    userId: uuid('user_id').notNull(),
    appId: text('app_id').default('boring-ui').notNull(),
    settings: jsonb().default({}).notNull(),
    email: text().default('').notNull(),
    displayName: text('display_name').default('').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({
      columns: [table.userId, table.appId],
      name: 'user_settings_pkey',
    }),
  ],
)
