/**
 * Drizzle ORM schema — will be populated by `drizzle-kit pull` from the
 * existing Neon DB (see bd-fus66). This placeholder ensures the project
 * structure is valid and drizzle.config.ts resolves.
 *
 * DO NOT define tables manually here during dual-stack period.
 * Use `npx drizzle-kit pull` to generate from the live database.
 */

// Placeholder — schema will be generated by drizzle-kit pull
export {}
