import type { HostVirtualSingletonModule } from "./hostModules.js"

/**
 * Named exports re-published by each generated singleton shim module.
 *
 * These lists mirror the real modules' export surfaces: a plugin importing a
 * name that is missing here fails with a named-export SyntaxError, so entries
 * are added when the underlying package gains an export.
 */

const WORKSPACE_ROOT_SINGLETON_EXPORTS = [
  "bootstrap",
  "PluginError",
  "CatalogRegistry",
  "useCommands",
  "useActivePanels",
  "useCatalogs",
  "PluginErrorBoundary",
  "PluginErrorProvider",
  "usePluginErrors",
  "WorkspacePluginClientProvider",
  "createWorkspacePluginClient",
  "useWorkspacePluginClient",
  "filesystemPlugin",
  "emitFilesystemAgentFileChange",
  "useAutoOpenAgentFiles",
  "onFilesystemChanged",
  "useFilePane",
  "WorkspaceFilesProvider",
  "useApiBaseUrl",
  "useHasWorkspaceFilesProvider",
  "useWorkspaceRequestId",
  "readFileRecords",
  "filesystemEvents",
  "cn",
  "PanelRegistry",
  "WorkspaceSourceRegistry",
  "CommandRegistry",
  "SurfaceResolverRegistry",
  "RegistryProvider",
  "useRegistry",
  "useWorkspaceSourceRegistry",
  "useCommandRegistry",
  "useCatalogRegistry",
  "useSurfaceResolverRegistry",
  "WORKSPACE_OPEN_PATH_SURFACE_KIND",
  "getFileIcon",
  "DockviewShell",
  "PanelChrome",
  "useDockviewApi",
  "IdeLayout",
  "buildIdeLayout",
  "ChatLayout",
  "buildChatLayout",
  "TopBar",
  "ResponsiveDockviewShell",
  "useEditorLifecycle",
  "buildFullPagePanelHref",
  "useFullPagePanelHref",
  "usePanelRenderMode",
  "useIsFullPagePanel",
  "useViewportBreakpoint",
  "useResponsiveSidebarCollapse",
  "useArtifactPanels",
  "useArtifactRouting",
  "useKeyboardShortcuts",
  "formatShortcut",
  "CommandPalette",
  "WorkspaceLoadingState",
  "ArtifactSurfacePane",
  "EmptyPane",
  "CodeEditorPane",
  "FileTreePane",
  "FileTreeView",
  "MarkdownEditorPane",
  "definePanel",
  "createShadcnTheme",
  "events",
  "useEvent",
  "userMeta",
  "agentMeta",
  "emitAgentData",
  "toast",
  "Toaster",
  "dismissToast",
  "createBridge",
  "createBridgeClient",
  "postUiCommand",
  "UI_COMMAND_EVENT",
  "WorkspaceLink",
  "workspaceLinkCommand",
  "workspaceLinkHref",
  "openFileSchema",
  "openPanelSchema",
  "closePanelSchema",
  "notificationSchema",
  "navigateToLineSchema",
  "expandToFileSchema",
  "MAX_PANELS",
  "PanelErrorBoundary",
  "CodeEditor",
  "FileTree",
  "MarkdownEditor",
  "SessionList",
  "SessionBrowser",
  "SurfaceShell",
  "WorkbenchLeftPane",
  "WorkspaceProvider",
  "ThemeProvider",
  "useTheme",
  "useWorkspaceBridge",
  "useWorkspaceContext",
  "useWorkspaceContextOptional",
  "useWorkspaceChatPanel",
  "useWorkspaceAttention",
  "createWorkspaceStore",
  "bindStore",
  "useActiveFile",
  "useActivePanel",
  "useSidebarState",
  "useSetSidebar",
  "useOpenPanels",
  "useDirtyFiles",
  "useThemePreference",
  "useHydrationComplete",
  "useResetLayout",
] as const

const WORKSPACE_PLUGIN_SINGLETON_EXPORTS = [
  "captureFrontPlugin",
  "createCapturingBoringFrontAPI",
  "definePlugin",
  "validateBoringPluginManifest",
  "isSafePluginRelativePath",
  "isValidBoringPluginId",
  "WORKSPACE_OPEN_PATH_SURFACE_KIND",
] as const

const WORKSPACE_EVENTS_SINGLETON_EXPORTS = [
  "events",
  "userMeta",
  "agentMeta",
  "remoteMeta",
  "workspaceEvents",
  "WORKSPACE_PLUGIN_ID",
  "WORKSPACE_UI_COMMAND_EVENT",
  "WORKSPACE_EDITOR_SAVE_START_EVENT",
  "WORKSPACE_EDITOR_SAVE_END_EVENT",
  "WORKSPACE_PANEL_UPDATE_EVENT",
  "WORKSPACE_PANEL_CLOSE_EVENT",
  "WORKSPACE_AGENT_DATA_EVENT",
  "useEvent",
  "emitAgentData",
] as const

export const RUNTIME_SINGLETON_EXPORTS: Partial<Record<HostVirtualSingletonModule, readonly string[]>> = {
  react: [
    "Activity",
    "Children",
    "Component",
    "Fragment",
    "Profiler",
    "PureComponent",
    "StrictMode",
    "Suspense",
    "__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE",
    "__COMPILER_RUNTIME",
    "act",
    "cache",
    "cacheSignal",
    "captureOwnerStack",
    "cloneElement",
    "createContext",
    "createElement",
    "createRef",
    "forwardRef",
    "isValidElement",
    "lazy",
    "memo",
    "startTransition",
    "unstable_useCacheRefresh",
    "use",
    "useActionState",
    "useCallback",
    "useContext",
    "useDebugValue",
    "useDeferredValue",
    "useEffect",
    "useEffectEvent",
    "useId",
    "useImperativeHandle",
    "useInsertionEffect",
    "useLayoutEffect",
    "useMemo",
    "useOptimistic",
    "useReducer",
    "useRef",
    "useState",
    "useSyncExternalStore",
    "useTransition",
    "version",
  ],
  "react-dom": [
    "__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE",
    "createPortal",
    "flushSync",
    "preconnect",
    "prefetchDNS",
    "preinit",
    "preinitModule",
    "preload",
    "preloadModule",
    "requestFormReset",
    "unstable_batchedUpdates",
    "useFormState",
    "useFormStatus",
    "version",
  ],
  "react-dom/client": ["createRoot", "hydrateRoot", "version"],
  "react/jsx-runtime": ["Fragment", "jsx", "jsxs"],
  "react/jsx-dev-runtime": ["Fragment", "jsxDEV"],
  "@hachej/boring-workspace": WORKSPACE_ROOT_SINGLETON_EXPORTS,
  "@hachej/boring-workspace/plugin": WORKSPACE_PLUGIN_SINGLETON_EXPORTS,
  "@hachej/boring-workspace/events": WORKSPACE_EVENTS_SINGLETON_EXPORTS,
}
