export { PanelRegistry } from "./PanelRegistry"
export { CommandRegistry } from "./CommandRegistry"
export { RegistryProvider, useRegistry, useCommandRegistry } from "./RegistryProvider"
export { getFileIcon } from "./getFileIcon"
export type { PanelConfig, PanelRegistration, SyncPanelConfig, LazyPanelConfig, CommandConfig } from "./types"
