export const BORING_AUTOMATION_ERROR_CODES = {
  INVALID_BODY: "BORING_AUTOMATION_INVALID_BODY",
  INVALID_CRON: "BORING_AUTOMATION_INVALID_CRON",
  INVALID_TIMEZONE: "BORING_AUTOMATION_INVALID_TIMEZONE",
  INVALID_MODEL: "BORING_AUTOMATION_INVALID_MODEL",
  AUTOMATION_NOT_FOUND: "BORING_AUTOMATION_NOT_FOUND",
  RUN_NOT_FOUND: "BORING_AUTOMATION_RUN_NOT_FOUND",
  RUN_ALREADY_ACTIVE: "BORING_AUTOMATION_RUN_ALREADY_ACTIVE",
  RUN_ALREADY_RECORDED: "BORING_AUTOMATION_RUN_ALREADY_RECORDED",
  RUN_EXECUTOR_UNAVAILABLE: "BORING_AUTOMATION_RUN_EXECUTOR_UNAVAILABLE",
  TRIGGER_FORBIDDEN: "BORING_AUTOMATION_TRIGGER_FORBIDDEN",
  RUN_FAILED: "BORING_AUTOMATION_RUN_FAILED",
} as const

export type BoringAutomationErrorCode = typeof BORING_AUTOMATION_ERROR_CODES[keyof typeof BORING_AUTOMATION_ERROR_CODES]
