export const BORING_AUTOMATION_ERROR_CODES = {
  INVALID_BODY: "BORING_AUTOMATION_INVALID_BODY",
  AUTOMATION_NOT_FOUND: "BORING_AUTOMATION_NOT_FOUND",
  RUN_NOT_FOUND: "BORING_AUTOMATION_RUN_NOT_FOUND",
} as const

export type BoringAutomationErrorCode = typeof BORING_AUTOMATION_ERROR_CODES[keyof typeof BORING_AUTOMATION_ERROR_CODES]
