// Better-auth core schema is generated by `pnpm auth:generate-schema`.
// Keep this as the single import point for drizzle.config.ts and migration tooling.
export * from '../../../drizzle/schema.js'

import { pgTable, text, uuid, jsonb, timestamp, primaryKey, index, integer, bigint, boolean, uniqueIndex, check, customType } from 'drizzle-orm/pg-core'
import { relations, sql } from 'drizzle-orm'
import { users } from '../../../drizzle/schema.js'

const bytea = customType<{ data: Uint8Array; driverData: string }>({
  dataType() {
    return 'bytea'
  },
})

export const userSettings = pgTable(
  'user_settings',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    appId: text('app_id').notNull(),
    displayName: text('display_name').notNull().default(''),
    email: text('email').notNull().default(''),
    settings: jsonb('settings').notNull().default({}),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.appId] }),
    index('user_settings_user_id_idx').on(table.userId),
  ],
)

export const userSettingsRelations = relations(userSettings, ({ one }) => ({
  user: one(users, {
    fields: [userSettings.userId],
    references: [users.id],
  }),
}))

export const workspaces = pgTable(
  'workspaces',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    appId: text('app_id').notNull(),
    name: text('name').notNull(),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    deletedAt: timestamp('deleted_at'),
    isDefault: boolean('is_default').notNull().default(false),
  },
  (table) => [
    index('workspaces_created_by_idx').on(table.createdBy),
    uniqueIndex('idx_workspaces_default_per_user_app')
      .on(table.createdBy, table.appId)
      .where(sql`${table.isDefault} = true`),
  ],
)

export const workspacesRelations = relations(workspaces, ({ one }) => ({
  creator: one(users, {
    fields: [workspaces.createdBy],
    references: [users.id],
  }),
}))

export const workspaceMembers = pgTable(
  'workspace_members',
  {
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'no action' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    role: text('role').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.userId] }),
    index('workspace_members_user_id_idx').on(table.userId),
    check('workspace_members_role_check', sql`${table.role} IN ('owner', 'editor', 'viewer')`),
  ],
)

export const workspaceMembersRelations = relations(workspaceMembers, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [workspaceMembers.workspaceId],
    references: [workspaces.id],
  }),
  user: one(users, {
    fields: [workspaceMembers.userId],
    references: [users.id],
  }),
}))

export const workspaceSettings = pgTable(
  'workspace_settings',
  {
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'no action' }),
    key: text('key').notNull(),
    value: bytea('value').notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.key] }),
  ],
)

export const workspaceSettingsRelations = relations(workspaceSettings, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [workspaceSettings.workspaceId],
    references: [workspaces.id],
  }),
}))

export const workspaceRuntimes = pgTable(
  'workspace_runtimes',
  {
    workspaceId: uuid('workspace_id')
      .primaryKey()
      .references(() => workspaces.id),
    spriteUrl: text('sprite_url'),
    spriteName: text('sprite_name'),
    state: text('state').notNull().default('pending'),
    lastError: text('last_error'),
    volumePath: text('volume_path'),
    lastErrorOp: text('last_error_op'),
    sandboxProvider: text('sandbox_provider'),
    sandboxId: text('sandbox_id'),
    sandboxStatus: text('sandbox_status'),
    sandboxSnapshotId: text('sandbox_snapshot_id'),
    sandboxCreatedAt: timestamp('sandbox_created_at'),
    sandboxLastUsedAt: timestamp('sandbox_last_used_at'),
    sandboxLastSeenAt: timestamp('sandbox_last_seen_at'),
    sandboxExpiresAt: timestamp('sandbox_expires_at'),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
    provisioningStep: text('provisioning_step'),
    stepStartedAt: timestamp('step_started_at'),
  },
  (table) => [
    check(
      'workspace_runtimes_state_check',
      sql`${table.state} IN ('pending', 'ready', 'error')`,
    ),
  ],
)

export const workspaceRuntimesRelations = relations(
  workspaceRuntimes,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceRuntimes.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspaceRuntimeResources = pgTable(
  'workspace_runtime_resources',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    purpose: text('purpose').notNull().default('main'),
    provider: text('provider').notNull(),
    handleKind: text('handle_kind').notNull(),
    stableKey: text('stable_key'),
    providerResourceId: text('provider_resource_id'),
    parentResourceId: uuid('parent_resource_id'),
    state: text('state').notNull(),
    persistenceMode: text('persistence_mode').notNull(),
    config: jsonb('config').notNull().default({}),
    providerMeta: jsonb('provider_meta').notNull().default({}),
    lastError: text('last_error'),
    lastErrorCode: text('last_error_code'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
    lastSeenAt: timestamp('last_seen_at'),
    lastUsedAt: timestamp('last_used_at'),
    expiresAt: timestamp('expires_at'),
    generation: integer('generation').notNull().default(0),
  },
  (table) => [
    uniqueIndex('workspace_runtime_resources_active_idx')
      .on(table.workspaceId, table.kind, table.purpose, table.provider)
      .where(sql`${table.state} <> 'deleted'`),
    index('workspace_runtime_resources_workspace_kind_idx').on(table.workspaceId, table.kind),
    index('workspace_runtime_resources_provider_stable_key_idx').on(table.provider, table.stableKey),
    index('workspace_runtime_resources_provider_resource_id_idx').on(table.provider, table.providerResourceId),
  ],
)

export const workspaceRuntimeResourcesRelations = relations(
  workspaceRuntimeResources,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceRuntimeResources.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspaceInvites = pgTable(
  'workspace_invites',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    email: text('email').notNull(),
    tokenHash: text('token_hash').notNull(),
    role: text('role').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    acceptedAt: timestamp('accepted_at'),
    failedAttempts: integer('failed_attempts').notNull().default(0),
    lockedUntil: timestamp('locked_until'),
    createdBy: uuid('created_by').references(() => users.id, {
      onDelete: 'restrict',
    }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('workspace_invites_token_hash_idx').on(table.tokenHash),
    index('workspace_invites_workspace_id_idx').on(table.workspaceId),
    check(
      'workspace_invites_role_check',
      sql`${table.role} IN ('owner', 'editor', 'viewer')`,
    ),
  ],
)

export const workspaceInvitesRelations = relations(
  workspaceInvites,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceInvites.workspaceId],
      references: [workspaces.id],
    }),
    creator: one(users, {
      fields: [workspaceInvites.createdBy],
      references: [users.id],
    }),
  }),
)

export const idempotencyKeys = pgTable(
  'idempotency_keys',
  {
    key: text('key').primaryKey(),
    scope: text('scope').notNull(),
    responseStatus: integer('response_status').notNull(),
    responseBody: jsonb('response_body').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    index('idempotency_keys_created_at_idx').on(table.createdAt),
  ],
)

// --- Usage metering -------------------------------------------------------
// Product-neutral credit/usage primitives consumed through
// PostgresMeteringStore. Amounts are integer micros of a host-defined
// currency unit; the embedding app owns pricing, currency, and grant policy.

export const creditGrants = pgTable(
  'boring_credit_grants',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    userId: text('user_id').notNull(),
    amountMicros: bigint('amount_micros', { mode: 'number' }).notNull(),
    reason: text('reason').notNull(),
    expiresAt: timestamp('expires_at'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('boring_credit_grants_user_reason_idx').on(table.userId, table.reason),
    check('boring_credit_grants_amount_check', sql`${table.amountMicros} > 0`),
  ],
)

// One row per purchase order, keyed by the provider order id (PRIMARY KEY) so the
// purchase lifecycle is globally idempotent per order. status models the lifecycle:
//   'granted'  — credits were minted for this order
//   'refunded' — refunded/disputed; either a tombstone written BEFORE any grant
//                (user_id/amount_micros null) so a late order_created never grants,
//                or a granted row transitioned after revocation.
// userId/amountMicros are nullable to allow a refund-before-grant tombstone.
export const creditPurchases = pgTable(
  'boring_credit_purchases',
  {
    orderId: text('order_id').primaryKey(),
    userId: text('user_id'),
    amountMicros: bigint('amount_micros', { mode: 'number' }),
    status: text('status').notNull().default('granted'),
    source: text('source').notNull().default('lemonsqueezy'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    refundedAt: timestamp('refunded_at'),
  },
  (table) => [
    index('boring_credit_purchases_user_idx').on(table.userId),
    check('boring_credit_purchases_amount_check', sql`${table.amountMicros} IS NULL OR ${table.amountMicros} > 0`),
    check('boring_credit_purchases_status_check', sql`${table.status} IN ('granted', 'refunded')`),
  ],
)

export const usageReservations = pgTable(
  'boring_usage_reservations',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    userId: text('user_id').notNull(),
    workspaceId: text('workspace_id'),
    sessionId: text('session_id'),
    runId: text('run_id').notNull(),
    source: text('source').notNull().default(''),
    amountMicros: bigint('amount_micros', { mode: 'number' }).notNull(),
    status: text('status').notNull().default('active'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    expiresAt: timestamp('expires_at').notNull(),
  },
  (table) => [
    uniqueIndex('boring_usage_reservations_active_run_idx')
      .on(table.runId)
      .where(sql`${table.status} = 'active'`),
    index('boring_usage_reservations_user_status_idx').on(table.userId, table.status, table.expiresAt),
    check('boring_usage_reservations_amount_check', sql`${table.amountMicros} > 0`),
    check(
      'boring_usage_reservations_status_check',
      sql`${table.status} IN ('active', 'settled', 'released', 'expired')`,
    ),
  ],
)

export const usageLedger = pgTable(
  'boring_usage_ledger',
  {
    /** Caller-provided stable usage id; the idempotency key for inserts. */
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    workspaceId: text('workspace_id'),
    sessionId: text('session_id'),
    runId: text('run_id'),
    messageId: text('message_id'),
    source: text('source').notNull().default(''),
    provider: text('provider'),
    model: text('model'),
    inputTokens: bigint('input_tokens', { mode: 'number' }).notNull().default(0),
    outputTokens: bigint('output_tokens', { mode: 'number' }).notNull().default(0),
    cacheReadTokens: bigint('cache_read_tokens', { mode: 'number' }).notNull().default(0),
    cacheWriteTokens: bigint('cache_write_tokens', { mode: 'number' }).notNull().default(0),
    providerCostMicros: bigint('provider_cost_micros', { mode: 'number' }).notNull().default(0),
    billedCostMicros: bigint('billed_cost_micros', { mode: 'number' }).notNull(),
    stopReason: text('stop_reason'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    index('boring_usage_ledger_user_created_idx').on(table.userId, table.createdAt),
    index('boring_usage_ledger_run_idx').on(table.runId),
    check('boring_usage_ledger_billed_check', sql`${table.billedCostMicros} >= 0`),
    check(
      'boring_usage_ledger_tokens_check',
      sql`${table.inputTokens} >= 0 AND ${table.outputTokens} >= 0 AND ${table.cacheReadTokens} >= 0 AND ${table.cacheWriteTokens} >= 0 AND ${table.providerCostMicros} >= 0`,
    ),
  ],
)

export const telemetryEvents = pgTable(
  'telemetry_events',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    appId: text('app_id').notNull(),
    eventName: text('event_name').notNull(),
    distinctId: text('distinct_id').notNull().default('anonymous'),
    properties: jsonb('properties').notNull().default({}),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    index('telemetry_events_app_created_at_idx').on(table.appId, table.createdAt),
    index('telemetry_events_event_name_idx').on(table.eventName),
  ],
)
