// Better-auth core schema is generated by `pnpm auth:generate-schema`.
// Keep this as the single import point for drizzle.config.ts and migration tooling.
export * from '../../../drizzle/schema.js'

import { pgTable, text, uuid, jsonb, timestamp, primaryKey, index, boolean, uniqueIndex, check, customType } from 'drizzle-orm/pg-core'
import { relations, sql } from 'drizzle-orm'
import { users } from '../../../drizzle/schema.js'

const bytea = customType<{ data: Uint8Array; driverData: string }>({
  dataType() {
    return 'bytea'
  },
})

export const userSettings = pgTable(
  'user_settings',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    appId: text('app_id').notNull(),
    displayName: text('display_name').notNull().default(''),
    email: text('email').notNull().default(''),
    settings: jsonb('settings').notNull().default({}),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.appId] }),
    index('user_settings_user_id_idx').on(table.userId),
  ],
)

export const userSettingsRelations = relations(userSettings, ({ one }) => ({
  user: one(users, {
    fields: [userSettings.userId],
    references: [users.id],
  }),
}))

export const workspaces = pgTable(
  'workspaces',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    appId: text('app_id').notNull(),
    name: text('name').notNull(),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    deletedAt: timestamp('deleted_at'),
    isDefault: boolean('is_default').notNull().default(false),
    machineId: text('machine_id'),
    volumeId: text('volume_id'),
    flyRegion: text('fly_region'),
  },
  (table) => [
    index('workspaces_created_by_idx').on(table.createdBy),
    uniqueIndex('idx_workspaces_default_per_user_app')
      .on(table.createdBy, table.appId)
      .where(sql`${table.isDefault} = true`),
  ],
)

export const workspacesRelations = relations(workspaces, ({ one }) => ({
  creator: one(users, {
    fields: [workspaces.createdBy],
    references: [users.id],
  }),
}))

export const workspaceMembers = pgTable(
  'workspace_members',
  {
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'no action' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    role: text('role').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.userId] }),
    index('workspace_members_user_id_idx').on(table.userId),
    check('workspace_members_role_check', sql`${table.role} IN ('owner', 'editor', 'viewer')`),
  ],
)

export const workspaceMembersRelations = relations(workspaceMembers, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [workspaceMembers.workspaceId],
    references: [workspaces.id],
  }),
  user: one(users, {
    fields: [workspaceMembers.userId],
    references: [users.id],
  }),
}))

export const workspaceSettings = pgTable(
  'workspace_settings',
  {
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'no action' }),
    key: text('key').notNull(),
    value: bytea('value').notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.key] }),
  ],
)

export const workspaceSettingsRelations = relations(workspaceSettings, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [workspaceSettings.workspaceId],
    references: [workspaces.id],
  }),
}))

export const workspaceRuntimes = pgTable(
  'workspace_runtimes',
  {
    workspaceId: uuid('workspace_id')
      .primaryKey()
      .references(() => workspaces.id),
    spriteUrl: text('sprite_url'),
    spriteName: text('sprite_name'),
    state: text('state').notNull().default('pending'),
    lastError: text('last_error'),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
    provisioningStep: text('provisioning_step'),
    stepStartedAt: timestamp('step_started_at'),
  },
  (table) => [
    check(
      'workspace_runtimes_state_check',
      sql`${table.state} IN ('pending', 'provisioning', 'ready', 'error')`,
    ),
  ],
)

export const workspaceRuntimesRelations = relations(
  workspaceRuntimes,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceRuntimes.workspaceId],
      references: [workspaces.id],
    }),
  }),
)

export const workspaceInvites = pgTable(
  'workspace_invites',
  {
    id: uuid('id')
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    email: text('email').notNull(),
    tokenHash: text('token_hash').notNull(),
    role: text('role').notNull(),
    expiresAt: timestamp('expires_at')
      .notNull()
      .default(sql`now() + interval '7 days'`),
    acceptedAt: timestamp('accepted_at'),
    createdBy: uuid('created_by').references(() => users.id, {
      onDelete: 'restrict',
    }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('workspace_invites_token_hash_idx').on(table.tokenHash),
    index('workspace_invites_workspace_id_idx').on(table.workspaceId),
    check(
      'workspace_invites_role_check',
      sql`${table.role} IN ('owner', 'editor', 'viewer')`,
    ),
  ],
)

export const workspaceInvitesRelations = relations(
  workspaceInvites,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceInvites.workspaceId],
      references: [workspaces.id],
    }),
    creator: one(users, {
      fields: [workspaceInvites.createdBy],
      references: [users.id],
    }),
  }),
)
