export const ASK_USER_ERROR_CODES = {
  PENDING_EXISTS: "ASK_USER_PENDING_EXISTS",
  QUESTION_NOT_FOUND: "ASK_USER_QUESTION_NOT_FOUND",
  QUESTION_ABANDONED: "ASK_USER_QUESTION_ABANDONED",
  QUESTION_NOT_READY: "ASK_USER_QUESTION_NOT_READY",
  SCHEMA_INVALID: "ASK_USER_SCHEMA_INVALID",
  ANSWER_INVALID: "ASK_USER_ANSWER_INVALID",
  SESSION_MISMATCH: "ASK_USER_SESSION_MISMATCH",
  UI_UNAVAILABLE: "ASK_USER_UI_UNAVAILABLE",
  ALREADY_ANSWERED: "ASK_USER_ALREADY_ANSWERED",
  ALREADY_CANCELLED: "ASK_USER_ALREADY_CANCELLED",
  UNAUTHORIZED: "ASK_USER_UNAUTHORIZED",
  UI_ACK_TIMEOUT: "ASK_USER_UI_ACK_TIMEOUT",
  RATE_LIMITED: "ASK_USER_RATE_LIMITED",
  RUNTIME_UNAVAILABLE: "ASK_USER_RUNTIME_UNAVAILABLE",
  BRIDGE_ERROR: "ASK_USER_BRIDGE_ERROR",
} as const

export type AskUserErrorCode = (typeof ASK_USER_ERROR_CODES)[keyof typeof ASK_USER_ERROR_CODES]

export const ASK_USER_ERROR_CODE_VALUES = Object.values(ASK_USER_ERROR_CODES) as AskUserErrorCode[]
