import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const vars=Object.fromEntries(readFileSync('/home/ubuntu/projects/boring-hub/app-runner/.dev.vars','utf8').split('\n').filter(x=>x&&!x.startsWith('#')).map(x=>x.split(/=(.*)/s).slice(0,2)))
const ws='proof', name=`guestbook-${Date.now().toString(36)}`, user={id:'proof-user',name:'Proof User'}
const app=`export default { async fetch(req,env){ const u=new URL(req.url); if(u.pathname==='/api/entries'){ env.db.execute('CREATE TABLE IF NOT EXISTS entries (name TEXT)'); if(req.method==='POST'){const b=await req.json();env.db.execute('INSERT INTO entries(name) VALUES (?)',[b.name]);return Response.json({ok:true})} let {rows}=env.db.execute('SELECT name FROM entries'); if(!rows.length){env.db.execute('INSERT INTO entries(name) VALUES (?)',['Ada']);rows=env.db.execute('SELECT name FROM entries').rows} return Response.json({entries:rows}) } return new Response('not found',{status:404}) }}`
const files={'app/index.js':app,'app/index.html':'<!doctype html><link rel="stylesheet" href="style.css"><main><h1>Guestbook</h1><ul id="entries"></ul></main><script src="client.js"></script>','app/style.css':'body{font-family:sans-serif} h1{color:rgb(12,80,140)}','app/client.js':`fetch('api/entries').then(r=>r.json()).then(x=>{document.querySelector('#entries').innerHTML=x.entries.map(e=>'<li>'+e.name+'</li>').join('')})`}
const auth={authorization:`Bearer ${vars.APP_RUNNER_TOKEN}`,'content-type':'application/json','x-boring-user':JSON.stringify(user),'x-boring-workspace':ws}
let r=await fetch(`http://127.0.0.1:9877/w/${ws}/${name}/publish`,{method:'POST',headers:auth,body:JSON.stringify({kind:'app',files,message:'browser proof'})}); if(!r.ok) throw new Error(await r.text())
r=await fetch(`http://127.0.0.1:9877/w/${ws}/${name}/signed-url`,{method:'POST',headers:auth}); const {url}=await r.json()
const browser=await chromium.launch({headless:true}); const page=await browser.newPage(); const seen=[]; page.on('response',x=>seen.push([new URL(x.url()).pathname,x.status()])); await page.goto(url,{waitUntil:'networkidle'}); await page.waitForSelector('#entries li'); const body=(await page.locator('body').innerText()).trim(); await page.screenshot({path:'/tmp/astra4-working-app.png'}); console.log(JSON.stringify({document:seen.find(x=>x[0]===`/w/${ws}/${name}/`),js:seen.find(x=>x[0].endsWith('/client.js')),css:seen.find(x=>x[0].endsWith('/style.css')),api:seen.find(x=>x[0].endsWith('/api/entries')),body})); await browser.close()
